from .categories_router import router as categories_router
from .courses_router import router as courses_router
from .levels_router import router as difficulties_router
from .lessons_router import router as lessons_router
from .roles_router import router as roles_router
from .users_router import router as users_router
from .completed_lessons_router import router as completed_lessons_router
from .courses_lessons_router import router as courses_lessons_router
from .courses_records_router import router as courses_records_router